// Install packages
const inquirer = require('inquirer');
console.log(inquirer)

// NEED TO HAVE TEST JS FILES AS WELL



// APP STARTS WITH PROMPTING ABOUT THE MANAGERS INFO



// AFTER MANAGER INFO THEN ASKED IF THEY WANT TO ADD IN ENGINEER, INTERN OR NO ONE


// SUPER IMPORTANT TO FIGURE OUT ALGORITHM FOR THE SEPCIFIC AMOUNT OF EMPLOYEES NEEDING TO BE CREATED ON THE HTML SIDE---- MIGHT HAVE TO DO WITH AN ARRAY AMOUNT THAT THEN GETS PUT INTO A FUNCTION TO CREATE IT AND THEN TEMPLATE THAT INTO THE GENERATE ````` SPOT


// NEED TO HAVE CLASSES FOR THE EMPLOYEE AND THEN EACH SUBCLASS (MANAGER, ENGINEER AND INTERN HAVE UNIQUE PROPERTIES AS WELL)


// AFTER SELECTING ADD NO MORE MEMBERS IT THEN RENDERS THE HTML AND CSS FILES OF THE EMPLOYEES

